name: cargo-machete
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


on:
  push:
    branches: [main]
    paths: ['Cargo.toml', '**/Cargo.toml']
  pull_request:
    paths: ['Cargo.toml', '**/Cargo.toml']
  schedule:
    - cron: '47 6 * * 4'  # weekly Thursday
  workflow_dispatch:
permissions:
  contents: read


jobs:
  machete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: bnjbvr/cargo-machete@c78956ec6ebce8ecde709a045eb4d7fbf4d0860b # main
